version: '3.8'

services:
  app:
    restart: always
    image: rozhoktest/hw-docker:latest
    ports:
    - '8081:8081'
    restart: always
    environment:
      DB_URIID: "mysql+pymysql://admin:adminadmin@hw-rozhkov-1.cqnhtawikwfv.eu-central-1.rds.amazonaws.com:3306/hw_rozhkov_db"
    networks:
    - mysqlnet


networks:
  mysqlnet:
    name: devops

volumes:
  mysql: